export interface Resource {
  title: string;
  url: string;
  description: string;
}

export interface YouTubeMeta {
  id: string; // 11-char video id
  url: string; // https://www.youtube.com/watch?v=ID
  embedUrl: string; // https://www.youtube.com/embed/ID?rel=0
  title: string; // best-known title (from list when API unavailable)
  description: string; // best-known description (from list when API unavailable)
  channelName: string; // performer/channel (best-effort)
  channelId?: string;
  publishedAt?: string; // ISO 8601
  duration?: string; // ISO8601 PT#M#S
  viewCount?: number;
  likeCount?: number;
  tags?: string[];
  thumbnails?: Array<{ url: string; width?: number; height?: number }>;
  captions?: Array<{ lang: string; autoGenerated?: boolean }>;
  chapters?: Array<{ start: number; title: string }>; // start in seconds
  oEmbed?: { html: string; width?: number; height?: number }; // iframe snippet
}

export interface ListicleItem {
  rank?: number; // ordered by appearance
  headline: string; // item title from list
  summary?: string; // blurb from list
  images?: Array<{ url: string; alt?: string }>;
  links?: string[]; // referenced links
  youtube?: YouTubeMeta; // present if the item has a YT video
}

export interface ListicleDB {
  sourceUrl: string;
  title: string;
  description: string;
  author?: string;
  updatedAt?: string; // ISO 8601
  itemCount?: number;
  items: ListicleItem[];
}
