// Resource categories for better organization and filtering
export type ResourceCategory =
  | 'learning'
  | 'books'
  | 'music'
  | 'audio'
  | 'video'
  | 'community'
  | 'events'
  | 'organizations'
  | 'culture'
  | 'grammar'
  | 'tools'
  | 'news';

// Enhanced Resource interface with categorization and metadata
export interface Resource {
  id?: string;
  title: string;
  titleEo?: string; // Esperanto translation of title
  url: string;
  description: string;
  descriptionEo?: string; // Esperanto translation of description
  category: ResourceCategory;
  tags?: string[];
  difficulty?: 'Beginner' | 'Intermediate' | 'Advanced' | 'All Levels';
  featured?: boolean; // Highlight as featured resource
  external?: boolean; // Indicates external link
  requiresAccount?: boolean; // Requires user account/registration
  cost?: 'Free' | 'Paid' | 'Freemium';
}

// Event resource for conferences, courses, and cultural events
export interface EventResource extends Resource {
  eventType: 'conference' | 'course' | 'workshop' | 'meetup' | 'cultural' | 'other';
  location?: string;
  frequency?: 'annual' | 'monthly' | 'weekly' | 'one-time' | 'ongoing';
  ageGroup?: string; // e.g., "Youth", "All Ages"
  requiresRegistration?: boolean;
}

// Organization resource for Esperanto associations and groups
export interface OrganizationResource extends Resource {
  organizationType: 'international' | 'national' | 'regional' | 'special-interest';
  country?: string; // ISO country code or name
  membershipRequired?: boolean;
  membershipUrl?: string;
}

// Music/Artist resource for Esperanto musicians and bands
export interface MusicResource {
  id: string;
  name: string;
  genre?: string;
  description?: string;
  descriptionEo?: string;
  links: {
    youtube?: string;
    spotify?: string;
    bandcamp?: string;
    website?: string;
    other?: string;
  };
  featured?: boolean;
}

// Grammar guide for language learning rules and explanations
export interface GrammarGuide {
  id: string;
  title: string;
  titleEo?: string;
  category: 'accusative' | 'pronouns' | 'verbs' | 'prepositions' | 'general';
  rules: Array<{
    rule: string;
    ruleEo?: string;
    examples?: Array<{
      esperanto: string;
      english: string;
    }>;
  }>;
  exceptions?: string[];
  externalUrl?: string;
}

export interface YouTubeMeta {
  id: string; // 11-char video id
  url: string; // https://www.youtube.com/watch?v=ID
  embedUrl: string; // https://www.youtube.com/embed/ID?rel=0
  title: string; // best-known title (from list when API unavailable)
  description: string; // best-known description (from list when API unavailable)
  channelName: string; // performer/channel (best-effort)
  channelId?: string;
  publishedAt?: string; // ISO 8601
  duration?: string; // ISO8601 PT#M#S
  viewCount?: number;
  likeCount?: number;
  tags?: string[];
  thumbnails?: Array<{ url: string; width?: number; height?: number }>;
  captions?: Array<{ lang: string; autoGenerated?: boolean }>;
  chapters?: Array<{ start: number; title: string }>; // start in seconds
  oEmbed?: { html: string; width?: number; height?: number }; // iframe snippet
}

export interface ListicleItem {
  rank?: number; // ordered by appearance
  headline: string; // item title from list
  summary?: string; // blurb from list
  images?: Array<{ url: string; alt?: string }>;
  links?: string[]; // referenced links
  youtube?: YouTubeMeta; // present if the item has a YT video
}

export interface ListicleDB {
  sourceUrl: string;
  title: string;
  description: string;
  author?: string;
  updatedAt?: string; // ISO 8601
  itemCount?: number;
  items: ListicleItem[];
}
